### ISSUE TITLE
Jhipster Online can't access Gitlab repositories

### ISSUE THREAD

**Issue by fleboulch** [jhipster/jhipster-online#93] opened 2019-01-11 10:31 UTC
I previously gave JHI Online access to my github account.  
It worked well but when I tried to plug it to my gitlab account it returned the following error :
`JHipster has failed to reach your Gitlab repositories.`

However when I go to my gitlab settings I'm seeing jhipster in my authorized apps

Do you have any clue about this error?

**Comment by jdubois** [comment] 2019-01-11 13:35
I just tested and it "works on my machine"... Maybe your tokens have been invalidated, can you click on the "authorized" button to refresh your tokens?

**Comment by fleboulch** [comment] 2019-01-11 13:55
I'm using 2 different mail address for github and gitlab. To authenticate to jhi online I'm using the same I'm using for github.

Are you using the same mail address on both gitlab and github?

**Comment by jdubois** [comment] 2019-01-11 13:56
I'm probably using the same, then I don't know how that could be an issue, we should only use your OAuth2 token to authentify (but this has been refactored since I wrote the original code, so it may have changed).

**Comment by fleboulch** [comment] 2019-01-11 14:36
I tried to create another jhi online account with my gitlab email address but authorize gitlab button is still not working.

I get the following error 505 :

```
{  
   "type":"https://www.jhipster.tech/problem/problem-with-message",
   "title":"Internal Server Error",
   "status":500,
   "detail":"Handler dispatch failed; nested exception is java.lang.Error: java.io.FileNotFoundException: https://gitlab.com/api/v4/groups/XXXXXXX/projects?per_page=100",
   "path":"/api/gitlab/save-token",
   "message":"error.http.500"
}
```

**Comment by jdubois** [comment] 2019-01-12 18:47
As I couldn't reproduce, @pascalgrimaud we can work on this on Tuesday as we will be at Ippon together.

**Comment by jdubois** [comment] 2019-02-06 16:41
I'm sorry we didn't work on this with @pascalgrimaud - and I just tested again, and had no problem at all...
Maybe you need to click on the "configure" button again?

**Comment by pascalgrimaud** [comment] 2019-02-07 07:52
Just tested again too, after resynchronizing my account and now, it works!
So I think we can close this.

Don't hesitate to comment if you still have the issue @fleboulch

**Comment by fleboulch** [comment] 2019-02-19 16:43
It's still not working. I revoked jhipster access in GitLab settings several times. I don't know why you can't reproduce it. It's quite weird.
Currently, I don't need this feature as I'm using GitHub for personal projects. Maybe some people will have the same issue as I and comment this thread. Let's see..

Thanks @pascalgrimaud and @jdubois for your investigation

**Comment by jdubois** [comment] 2019-02-19 17:00
@fleboulch I have a doubt here: are you using start.jhipster.tech to connect to the public GitLab instance? And not your own instance of JHispter Online connecting to an on-premise GitLab instance?

**Comment by fleboulch** [comment] 2019-02-22 21:57
I logged on `start.jhipster.tech` and after I clicked on "Authorize GitLab" button on the configure menu as I previously done for GitHub

**Comment by azizkhani** [comment] 2019-03-14 14:17
My account can not sync gitlab after . a few moth a go it works correctly but now dose not work to sync my repository . i revoke access and again dose not work .
my account : azizkhani

**Comment by jdubois** [comment] 2019-03-14 14:56
I'm really sorry as I can't reproduce here... No idea what we can do at the moment

**Comment by MareGeldenhuys** [comment] 2020-05-23 11:55
Running into this same issue from https://start.jhipster.tech/ accessing the public gitlab.com instance. When the callback is made to jhipster.tech, the service responds with a 500 Internal Service error from the save-token endpoint. I suspect this is due to Gitlab not registering the jhipster application, even though I have tried authorizing multiple times. Is there perhaps a manual method of registering the application instead as a workaround?

**Comment by jdubois** [comment] 2020-05-25 08:43
@MareGeldenhuys I have the same issue as you now, so something has changed, probably on the GitLab side (as we didn't update any code on this).
I believe this should be a new ticket, as here we are discussing on an older issue.

**Comment by atomfrede** [comment] 2020-05-25 09:08
I can reproduce it when trying authorize with gitlab. As my account is already registered everything works fine though. But I guess not for accounts which are not already registered.

**Comment by fleboulch** [comment] 2020-05-25 09:25
It's seems to be the same issue existing since January 2019 (or more). I've never succeed to sync my Gitlab account.
Can you re open this issue please? However, I don't know how to fix it but I can help

**Comment by jdubois** [comment] 2020-05-25 11:17
OK this seems important: so the issue is when you have not connected your account yet.
I'm adding a bug bounty here.

**Comment by atomfrede** [comment] 2020-05-25 11:39
We might be reconsider to switch from https://github.com/timols/java-gitlab-api to https://github.com/gitlab4j/gitlab4j-api which seems to be better maintained (but first let's make it work again).

**Comment by vishal423** [comment] 2020-05-25 14:44
If no one else is working on it, I can take a look on top of changes to upgrade to `v6.8`

**Comment by jdubois** [comment] 2020-05-25 17:59
@vishal423 I'm assigning this to you, I hope you're OK with this

**Comment by vishal423** [comment] 2020-05-25 19:42
@jdubois, I have raised PR with the solution. The issue was coming due to Cloudflare user-agent policies.

**Closed** 2020-05-26 04:53 UTC
Labels: $$ bug-bounty $$, $200

**Comment by jdubois** [comment] 2020-05-26 11:15
Thanks a lot @vishal423 !

**Comment by tonsV2** [comment] 2020-07-25 15:31
After facing the same issue as described here Google brought me here. In other words this is not working, at least not for me.

**Comment by SudharakaP** [comment] 2020-07-25 15:33
> After facing the same issue as described here, Google brought me here. In other words this is still not working, at least not for me.
> 
> To clarify a bit more, I tried to revoke the token and reauth a few times to no avail.

@tonsV2 : Thanks. I am working on a solution to this. This was reported at, #200
